---
- name: Apache server installed
  hosts: all
  tasks:
  - name: latest Apache version installed
    zypper:
      name: httpd
      state: latest
  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started
