- hosts: all
  tasks:
    - name: unmount /mercury/data 
      mount:
        path: /mercury/data
        src: 192.168.1.149:/volume1/data
        fstype: nfs
        state: unmounted
        opts: "rw,relatime,vers=3,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.1.149,mountvers=3,mountport=892,mountproto=udp,local_lock=none,addr=192.168.1.149"

    - name: Check if /mercury/data is empty
      find:
        paths: '/test/'
      register: files_found

    - name: Remove /mercury/data directory if empty
      file:
        path: /test
        state: absent
      when: files_found.matched == 0

