---
- name: Prepare www server
  hosts: all
  tasks:
  - name: latest nginx version installed
    zypper:
      name: nginx
      state: latest
  - name: nginx enabled and running
    service:
      name: nginx
      enabled: true
      state: started
  - name: chronyd enabled and running
    service:
      name: chronyd
      enabled: true
      state: started
